### ISSUE TITLE
npm install errors

### ISSUE THREAD

**Issue by sven-borkert** [nuxt-ui-pro/dashboard#24]
Hi,

I tried using this template, but an npm install floods me with errors:

> npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @typescript-eslint/eslint-plugin@7.8.0
npm WARN Found: eslint@9.2.0
npm WARN node_modules/eslint
npm WARN   dev eslint@"^9.2.0" from the root project
npm WARN   17 more (@eslint-community/eslint-utils, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer eslint@"^8.56.0" from @typescript-eslint/eslint-plugin@7.8.0
npm WARN node_modules/@nuxt/eslint-config/node_modules/@typescript-eslint/eslint-plugin
npm WARN   @typescript-eslint/eslint-plugin@"^7.8.0" from @nuxt/eslint-config@0.3.12
npm WARN   node_modules/@nuxt/eslint-config
npm WARN
npm WARN Conflicting peer dependency: eslint@8.57.0
npm WARN node_modules/eslint
npm WARN   peer eslint@"^8.56.0" from @typescript-eslint/eslint-plugin@7.8.0
npm WARN   node_modules/@nuxt/eslint-config/node_modules/@typescript-eslint/eslint-plugin
npm WARN     @typescript-eslint/eslint-plugin@"^7.8.0" from @nuxt/eslint-config@0.3.12
npm WARN     node_modules/@nuxt/eslint-config
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @typescript-eslint/parser@7.8.0
npm WARN Found: eslint@9.2.0
npm WARN node_modules/eslint
npm WARN   dev eslint@"^9.2.0" from the root project
npm WARN   17 more (@eslint-community/eslint-utils, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer eslint@"^8.56.0" from @typescript-eslint/parser@7.8.0
npm WARN node_modules/@nuxt/eslint-config/node_modules/@typescript-eslint/parser
npm WARN   @typescript-eslint/parser@"^7.8.0" from @nuxt/eslint-config@0.3.12
npm WARN   node_modules/@nuxt/eslint-config
npm WARN   1 more (@typescript-eslint/eslint-plugin)
npm WARN
npm WARN Conflicting peer dependency: eslint@8.57.0
npm WARN node_modules/eslint
npm WARN   peer eslint@"^8.56.0" from @typescript-eslint/parser@7.8.0
npm WARN   node_modules/@nuxt/eslint-config/node_modules/@typescript-eslint/parser
npm WARN     @typescript-eslint/parser@"^7.8.0" from @nuxt/eslint-config@0.3.12
npm WARN     node_modules/@nuxt/eslint-config
npm WARN     1 more (@typescript-eslint/eslint-plugin)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @typescript-eslint/utils@7.8.0
npm WARN Found: eslint@9.2.0
npm WARN node_modules/eslint
npm WARN   dev eslint@"^9.2.0" from the root project
npm WARN   17 more (@eslint-community/eslint-utils, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer eslint@"^8.56.0" from @typescript-eslint/utils@7.8.0
npm WARN node_modules/@nuxt/eslint-plugin/node_modules/@typescript-eslint/utils
npm WARN   @typescript-eslint/utils@"^7.8.0" from @nuxt/eslint-plugin@0.3.12
npm WARN   node_modules/@nuxt/eslint-plugin
npm WARN
npm WARN Conflicting peer dependency: eslint@8.57.0
npm WARN node_modules/eslint
npm WARN   peer eslint@"^8.56.0" from @typescript-eslint/utils@7.8.0
npm WARN   node_modules/@nuxt/eslint-plugin/node_modules/@typescript-eslint/utils
npm WARN     @typescript-eslint/utils@"^7.8.0" from @nuxt/eslint-plugin@0.3.12
npm WARN     node_modules/@nuxt/eslint-plugin
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @typescript-eslint/utils@7.8.0
npm WARN Found: eslint@9.2.0
npm WARN node_modules/eslint
npm WARN   dev eslint@"^9.2.0" from the root project
npm WARN   17 more (@eslint-community/eslint-utils, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer eslint@"^8.56.0" from @typescript-eslint/utils@7.8.0
npm WARN node_modules/@stylistic/eslint-plugin-plus/node_modules/@typescript-eslint/utils
npm WARN   @typescript-eslint/utils@"^7.8.0" from @stylistic/eslint-plugin-plus@2.1.0
npm WARN   node_modules/@stylistic/eslint-plugin-plus
npm WARN
npm WARN Conflicting peer dependency: eslint@8.57.0
npm WARN node_modules/eslint
npm WARN   peer eslint@"^8.56.0" from @typescript-eslint/utils@7.8.0
npm WARN   node_modules/@stylistic/eslint-plugin-plus/node_modules/@typescript-eslint/utils
npm WARN     @typescript-eslint/utils@"^7.8.0" from @stylistic/eslint-plugin-plus@2.1.0
npm WARN     node_modules/@stylistic/eslint-plugin-plus
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @typescript-eslint/utils@7.8.0
npm WARN Found: eslint@9.2.0
npm WARN node_modules/eslint
npm WARN   dev eslint@"^9.2.0" from the root project
npm WARN   17 more (@eslint-community/eslint-utils, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer eslint@"^8.56.0" from @typescript-eslint/utils@7.8.0
npm WARN node_modules/@stylistic/eslint-plugin-ts/node_modules/@typescript-eslint/utils
npm WARN   @typescript-eslint/utils@"^7.8.0" from @stylistic/eslint-plugin-ts@2.1.0
npm WARN   node_modules/@stylistic/eslint-plugin-ts
npm WARN
npm WARN Conflicting peer dependency: eslint@8.57.0
npm WARN node_modules/eslint
npm WARN   peer eslint@"^8.56.0" from @typescript-eslint/utils@7.8.0
npm WARN   node_modules/@stylistic/eslint-plugin-ts/node_modules/@typescript-eslint/utils
npm WARN     @typescript-eslint/utils@"^7.8.0" from @stylistic/eslint-plugin-ts@2.1.0
npm WARN     node_modules/@stylistic/eslint-plugin-ts
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @typescript-eslint/utils@7.8.0
npm WARN Found: eslint@9.2.0
npm WARN node_modules/eslint
npm WARN   dev eslint@"^9.2.0" from the root project
npm WARN   17 more (@eslint-community/eslint-utils, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer eslint@"^8.56.0" from @typescript-eslint/utils@7.8.0
npm WARN node_modules/eslint-plugin-import-x/node_modules/@typescript-eslint/utils
npm WARN   @typescript-eslint/utils@"^7.4.0" from eslint-plugin-import-x@0.5.0
npm WARN   node_modules/eslint-plugin-import-x
npm WARN
npm WARN Conflicting peer dependency: eslint@8.57.0
npm WARN node_modules/eslint
npm WARN   peer eslint@"^8.56.0" from @typescript-eslint/utils@7.8.0
npm WARN   node_modules/eslint-plugin-import-x/node_modules/@typescript-eslint/utils
npm WARN     @typescript-eslint/utils@"^7.4.0" from eslint-plugin-import-x@0.5.0
npm WARN     node_modules/eslint-plugin-import-x
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @typescript-eslint/type-utils@7.8.0
npm WARN Found: eslint@9.2.0
npm WARN node_modules/eslint
npm WARN   dev eslint@"^9.2.0" from the root project
npm WARN   17 more (@eslint-community/eslint-utils, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer eslint@"^8.56.0" from @typescript-eslint/type-utils@7.8.0
npm WARN node_modules/@nuxt/eslint-config/node_modules/@typescript-eslint/eslint-plugin/node_modules/@typescript-eslint/type-utils
npm WARN   @typescript-eslint/type-utils@"7.8.0" from @typescript-eslint/eslint-plugin@7.8.0
npm WARN   node_modules/@nuxt/eslint-config/node_modules/@typescript-eslint/eslint-plugin
npm WARN
npm WARN Conflicting peer dependency: eslint@8.57.0
npm WARN node_modules/eslint
npm WARN   peer eslint@"^8.56.0" from @typescript-eslint/type-utils@7.8.0
npm WARN   node_modules/@nuxt/eslint-config/node_modules/@typescript-eslint/eslint-plugin/node_modules/@typescript-eslint/type-utils
npm WARN     @typescript-eslint/type-utils@"7.8.0" from @typescript-eslint/eslint-plugin@7.8.0
npm WARN     node_modules/@nuxt/eslint-config/node_modules/@typescript-eslint/eslint-plugin
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @typescript-eslint/utils@7.8.0
npm WARN Found: eslint@9.2.0
npm WARN node_modules/eslint
npm WARN   dev eslint@"^9.2.0" from the root project
npm WARN   17 more (@eslint-community/eslint-utils, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer eslint@"^8.56.0" from @typescript-eslint/utils@7.8.0
npm WARN node_modules/@nuxt/eslint-config/node_modules/@typescript-eslint/eslint-plugin/node_modules/@typescript-eslint/utils
npm WARN   @typescript-eslint/utils@"7.8.0" from @typescript-eslint/eslint-plugin@7.8.0
npm WARN   node_modules/@nuxt/eslint-config/node_modules/@typescript-eslint/eslint-plugin
npm WARN   1 more (@typescript-eslint/type-utils)
npm WARN
npm WARN Conflicting peer dependency: eslint@8.57.0
npm WARN node_modules/eslint
npm WARN   peer eslint@"^8.56.0" from @typescript-eslint/utils@7.8.0
npm WARN   node_modules/@nuxt/eslint-config/node_modules/@typescript-eslint/eslint-plugin/node_modules/@typescript-eslint/utils
npm WARN     @typescript-eslint/utils@"7.8.0" from @typescript-eslint/eslint-plugin@7.8.0
npm WARN     node_modules/@nuxt/eslint-config/node_modules/@typescript-eslint/eslint-plugin
npm WARN     1 more (@typescript-eslint/type-utils)

What to do about this?

Regards,
Sven

**Comment by benjamincanac** [comment]
Those are only warnings from upstream packages (eslint), you can ignore them.
