### ISSUE TITLE
truncate UserDropdown

### ISSUE THREAD

**Issue by IgorKha** [nuxt-ui-pro/dashboard#25]
this not work:
https://github.com/nuxt-ui-pro/dashboard/blob/f94a5ff02a11ed27793136becc5e28dce45ad66a/components/UserDropdown.vue#L86
<img width="230" alt="Screenshot 2024-05-17 at 16 20 13" src="https://github.com/nuxt-ui-pro/dashboard/assets/2268209/e1126773-8d5c-46c7-a8f5-dd1d60ca39c9">

but this work it:
```
<template #account>
      <div class="truncate text-left">
        <p>
          Signed in as
        </p>
        <p class="truncate font-medium text-gray-900 dark:text-white">
          ben@nuxtlabs.com
        </p>
     </div>
</template>
 ```
 
<img width="241" alt="Screenshot 2024-05-17 at 16 27 11" src="https://github.com/nuxt-ui-pro/dashboard/assets/2268209/70a44b74-6b15-41b9-9227-0680c8ae685b">

**Comment by benjamincanac** [comment]
You can try setting `min-w-0` instead of `truncate` on the wrapper div.
