### ISSUE TITLE
More examples using tables

### ISSUE THREAD

**Issue by husayt** [nuxt-ui-pro/dashboard#29]
This is really useful template showcasing the power of Nuxt Ui pro. Would be great to see more pages with tables as this is what used a lot in dashboard like apps: simple tables, rich tables, tables with editors, tables with drilldowns and etc

Thanks.

**Comment by benjamincanac** [comment]
The `Table` used belong to Nuxt UI, you can find a complete example of its documentation: https://ui.nuxt.com/components/table#example
