### ISSUE TITLE
recommended way to mix with saas

### ISSUE THREAD

**Issue by lammerfalcon** [nuxt-ui-pro/dashboard#31]
it is better to have 2 separate repos SaaS and Dashboard, or for small SaaS better to combine 2 repos in 1?)
i know there is abstraction question, but I wonder how you imagine combining these two templates

**Comment by benjamincanac** [comment]
You can totally mix them up! I'd start with the `saas` template and then copy the dashboard template layouts / pages / components inside. You will have to rename the `default.vue` layout from dashboard into `dashboard.vue` and specify this in your dashboard pages using `definePageMeta`: https://nuxt.com/docs/api/utils/define-page-meta#defining-layout

**Comment by lammerfalcon** [comment]
> You can totally mix them up! I'd start with the `saas` template and then copy the dashboard template layouts / pages / components inside. You will have to rename the `default.vue` layout from dashboard into `dashboard.vue` and specify this in your dashboard pages using `definePageMeta`: https://nuxt.com/docs/api/utils/define-page-meta#defining-layout

Thank you! I started my SaaS boilerplate with Nuxt UI SaaS + Dashboard + NuxtHub. Very impressive ecosystem i think. Easy to use, easy to deploy!)
Instead of writing definePageMeta, i create middleware where i set layout if route path starts with /app, works perfect
