### ISSUE TITLE
Unable to find @ vueuse/nuxt @ 10.11.0 dependency.

### ISSUE THREAD

**Issue by 1532332928** [nuxt-ui-pro/dashboard#32]
```shell
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @vueuse/nuxt@^10.11.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by benjamincanac** [comment]
What version of `@nuxt/ui-pro` are you using?

**Comment by 1532332928** [comment]
> 您使用的是什么版本？`@nuxt/ui-pro`

yes

**Comment by benjamincanac** [comment]
What version are you using?

**Comment by 1532332928** [comment]
Downloaded directly from `npx nuxi init-t github:nuxt-ui-pro/dashboard`

**Comment by benjamincanac** [comment]
Yes but we update the templates on a regular basis so if you've downloaded it a month ago you might need to update the dependencies.
