### ISSUE TITLE
Pre-tranform error when running the template

### ISSUE THREAD

**Issue by Rednas83** [nuxt-ui-pro/dashboard#40]
**Server**
![image](https://github.com/user-attachments/assets/a22041cb-ddb7-4d42-8181-b8498d2b1da2)
**Client**
![image](https://github.com/user-attachments/assets/1692fa3d-fbe8-47ef-b992-5ee222041943)
**Info**
```
------------------------------
- Operating System: Windows_NT
- Node Version:     v20.15.0
- Nuxt Version:     3.12.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.6.0
- Builder:          -
- User Config:      extends, modules, ui, colorMode, routeRules, devtools, typescript, future, eslint, compatibilityDate
- Runtime Modules:  @nuxt/eslint@0.3.13, @nuxt/fonts@0.7.1, @nuxt/ui@2.17.0, @vueuse/nuxt@10.11.0
- Build Modules:    -
------------------------------
```
Tried upgrading nuxt and updating to the latest packages but still the same error.

Is it already compatible with node v20?

**Comment by benjamincanac** [comment]
I'm not sure where this error comes from but it looks like an upstream issue in nuxt, have you tried the latest `3.12.4` patch? 🤔

**Comment by Rednas83** [comment]
Same error after updating
```
------------------------------
- Operating System: Windows_NT
- Node Version:     v20.15.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.6.0
- Builder:          -
- User Config:      extends, modules, ui, colorMode, routeRules, devtools, typescript, future, eslint, compatibilityDate
- Runtime Modules:  @nuxt/eslint@0.4.0, @nuxt/fonts@0.7.1, @nuxt/ui@2.18.3, @vueuse/nuxt@10.11.0
- Build Modules:    -
------------------------------
```

I also have a missing license, but I am only running in development mode so I don't think that could be a problem
![image](https://github.com/user-attachments/assets/5ae20689-2431-4959-8407-4c332906847e)

Is it compatibly with node v20? I Remember I had a message to upgrade to v19 when installing.

**Comment by benjamincanac** [comment]
From what I guess from the error (I don't have a Windows to test), this might come from the `@nuxt/devtools`. Have you tried disabling it to see if it works?

**Comment by Rednas83** [comment]
Thanx. That worked for my windows machine. 
**nuxt.config.ts**
  devtools: {
    enabled: false,
  },
**client**
![image](https://github.com/user-attachments/assets/feeff6a8-ab7d-487c-8c42-f3a1a959b689)

Perhaps it can be mentioned in the docs?

**Comment by benjamincanac** [comment]
This should not be happening, it might be an upstream issue with one of the dependencies of `@nuxt/devtools`.
