### ISSUE TITLE
Date Time Picker not responsive

### ISSUE THREAD

**Issue by moshetanzer** [nuxt-ui-pro/dashboard#5]
Hi,

The date picker component is unusable on mobile portrait view. 

See screenshot below. 

Not sure which repo it is best open this in 
![image](https://github.com/nuxt-ui-pro/dashboard/assets/82201261/148cfaef-6086-46bf-b673-8b44b76ca2ba)

**Comment by moshetanzer** [comment]
Would you be happy to include a libary like https://github.com/nathanreyes/vue-screen-utils to make it responsive as suggested by v-calandar creator (another one of his libs) :) - or something custom? Also, should this not be implemented in ui docs whatever decicision is?

**Comment by benjamincanac** [comment]
Should be better now 😊 I've used [`useBreakpoints`](https://vueuse.org/core/useBreakpoints/#usebreakpoints) from VueUse, it avoids installing another dependency.

**Comment by moshetanzer** [comment]
neat ;) are you going to add to example on nuxt ui? or not necessary?

**Comment by benjamincanac** [comment]
I've updated the examples on `@nuxt/ui`: https://github.com/nuxt/ui/commit/7dd9ee528e3496fe357d9734904bf5e8bd8c8c89

**Comment by moshetanzer** [comment]
great! Keep it up!
