### ISSUE TITLE
Can't get PWA to work with UI Pro

### ISSUE THREAD

**Issue by mkelk** [nuxt-ui-pro/dashboard#56]
Do you have any working example of using UI Pro with PWA?
I seem to be struggling endlessly with confusion between the root dir (used in regulser Nuxt) and the app dir used by UI Pro.
Or maybe some pointers to how to structure the interplay of nuxt.config.js and package.json and (if using Netlify) netlify.toml.

It is quite critical for my business case and I would hate to abandon UI Pro.

Help would very much appreciated!!

Morten

**Comment by benjamincanac** [comment]
Would you mind sharing a reproduction of what's not working? This is too vague to help you.

**Comment by mkelk** [comment]
Maybe I'll make a small demo in github to show the problem. That would probably be the most concrete way to illustrate it!

**Comment by mkelk** [comment]
Hi Benjamin,

Here is more detail.

Take a look at https://github.com/mkelk/tst-ui-pro-pwa, the main branch
It is a fresh install of UI Pro Dashboard.

I have followed the guidelines for installing PWA. It partially works with a service-worker running, but the manifest is not registered and so the browser does not recognize the app as a PWA.

I have documented both installation and problem at the top of the README: https://github.com/mkelk/tst-ui-pro-pwa

I hope you can make sense of it.

Regards,
Morten

**Comment by mkelk** [comment]
Got it working (latest commit in https://github.com/mkelk/tst-ui-pro-pwa).
I was missing ` <VitePwaManifest />` in the actual pages.
