### ISSUE TITLE
Vue warning coming from DashboardPanel

### ISSUE THREAD

**Issue by systemizedrevenuebrandon** [nuxt-ui-pro/dashboard#64]
I saw a warning start popping up at one point and couldn't figure out what I did to cause it, spent around 20mins then I found it appears from using DashboardPanel component.

[Vue warn]: Template ref "el" used on a non-ref value. It will not work in the production build.

I did a fresh clone also and same warning appears.

**Comment by benjamincanac** [comment]
Duplicate nuxt/ui-pro#557.

This has been fixed already by https://github.com/nuxt/ui-pro/commit/badeb0e330c73533025d39723380a094d9d633ae and will be released in the next patch!
