### ISSUE TITLE
Can you please provide an example with an select item in a modal?

### ISSUE THREAD

**Issue by gigo1980** [nuxt-ui-pro/dashboard#7]
It is not clear how we can use the pro component `UDashboardModal`with a select element.

Can you provide an example in your demo App?

It is related to the following issue: https://github.com/nuxt/ui/issues/806

**Comment by jsayer101** [comment]
Hello, I agree that would appreciated.
For me, using the given answer, by setting
```js
:popper="{ strategy: 'fixed' }" :ui="{ width: 'w-24' }"
```

result in the popper taking full width of the page.

**Comment by jsayer101** [comment]
After further reading we should use 
```js
:popper="{ strategy: 'fixed' }" :ui-menu="{ width: 'w-96' }"
```

But this is not mentionned in the related issue. This could be improved by adding this to the docs so other users don't fall in this trap.
